# Generated by Django 4.0.4 on 2022-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_department_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
