# Generated by Django 4.0.4 on 2022-10-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_employee_salary_delete_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emp.employee'),
            preserve_default=False,
        ),
    ]
